services:

   #client is the service name and lushiro_client is the container name and we can acces the frontend using it domain name inside the compose project that is throught the internally established DNS system of that docker compose project. BUT THE THINGIES ACTUALLY RUN ON BROWSER AND CORS ALSO IS A BROWSER ONLY THING , so we use localhost instead of service names, service names won't work because we are not inside the container, and when frontend sends request to backend ,it is on the browser , not inside the container , the container is just a place to serve the files, not to host them. 
  client: 
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: lushiro_client:prod
    container_name: lushiro_prod_client
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - server
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: lushiro_server:prod
    container_name: lushiro_prod_server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CLIENT_URL=http://localhost:3000
      - atlas= $$atlas
    env_file:
      - ./server/.env
    restart: unless-stopped
 